### ISSUE TITLE
update email contact on readme?

### ISSUE THREAD

**Issue by sfoks** [EMscience/HydroBench#1]
Hi Dr. Moges, your readme.md on HydroBench features an email contact that no longer is available. Is there an updated contact where you can be reached? Thank you so much.

**Comment by EMscience** [comment]
Hi Sydney,
I recently moved to a new job and that email does not work anymore. You may reach me at edommele@gmail.com.
Best,
Edom

**Comment by sfoks** [comment]
Thank you Edom!
